[project]
name = "hellow-mcp"
version = "0.1.0"
description = "MCP server for a home Raspberry Pi"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastmcp>=4.0.11",
    "psutil>=7.2.2",
]

[project.scripts]
hellow-mcp = "hellow_mcp.server:main"

[build-system]
requires = ["uv_build>=0.8,<1"]
build-backend = "uv_build"
